# Generated by Django 5.1.7 on 2025-03-14 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='productos',
        ),
    ]
