# Generated by Django 5.1.7 on 2025-03-15 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_proveedor'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='proveedor',
            table='proveedores',
        ),
    ]
